/**
 * OpenVintage - Unified Hardware Database (HAL)
 * Accurate hardware specs and silicon limits for legacy Intel Mac platforms.
 */

import { HardwareProfile } from '../types';

export const LEGACY_MAC_HARDWARE_PROFILES: HardwareProfile[] = [
  {
    id: 'mbp-mid2012-15',
    systemName: 'MacBook Pro 15-inch (Mid 2012)',
    modelIdentifier: 'MacBookPro9,1',
    releaseYear: 2012,
    family: 'Ivy Bridge (2012)',
    cpu: {
      model: 'Intel Core i7-3615QM',
      architecture: 'x86_64',
      microarchitecture: 'Ivy Bridge',
      physicalCores: 4,
      logicalThreads: 8,
      baseClockGhz: 2.3,
      maxTurboGhz: 3.3,
      instructionSets: ['MMX', 'SSE4.2', 'AVX', 'VT-x', 'AES-NI'],
      tdpWatts: 45,
    },
    gpu: {
      vendor: 'Nvidia',
      model: 'GeForce GT 650M (Kepler) + Intel HD 4000',
      architecture: 'Kepler (GK107)',
      vramMB: 1024,
      pcieGen: 'PCIe 3.0 x8',
      nativeApis: {
        openGL: 'OpenGL 4.1 Core',
        openCL: 'OpenCL 1.2',
        metal: 'Metal 1.2 (Feature Set macOS_GPUFamily1_v1)',
        vulkan: 'Vulkan 1.0 (Limited MoltenVK)',
        directX: 'Direct3D 11.0',
      },
      limits: {
        maxTextureSize: 16384,
        maxColorAttachments: 8,
        computeSupported: true,
        tessellationSupported: true,
        geometryShaderSupported: true,
        anisotropicMax: 16,
        msaaMax: 8,
      },
      quirks: [
        'Automatic Graphics Switching (GMUX) can cause stalls during API switch',
        'VRAM limited to 1GB GDDR5; aggressive texture compression recommended',
      ],
    },
    ramMB: 8192,
    storageType: 'SATA SSD',
    efiBitness: '64-bit',
  },
  {
    id: 'macpro-mid2010-51',
    systemName: 'Mac Pro (Mid 2010)',
    modelIdentifier: 'MacPro5,1',
    releaseYear: 2010,
    family: 'Nehalem / Westmere (2009-2010)',
    cpu: {
      model: 'Dual Intel Xeon X5670 (Westmere-EP)',
      architecture: 'x86_64',
      microarchitecture: 'Westmere',
      physicalCores: 12,
      logicalThreads: 24,
      baseClockGhz: 2.93,
      maxTurboGhz: 3.33,
      instructionSets: ['MMX', 'SSE4.2', 'AES-NI', 'VT-d'],
      tdpWatts: 190,
    },
    gpu: {
      vendor: 'AMD',
      model: 'ATI Radeon HD 5770 (TeraScale 2)',
      architecture: 'TeraScale 2 (Evergreen)',
      vramMB: 1024,
      pcieGen: 'PCIe 2.0 x16',
      nativeApis: {
        openGL: 'OpenGL 3.3 / 4.1 (Partial)',
        openCL: 'OpenCL 1.2',
        metal: null,
        vulkan: null,
        directX: 'Direct3D 11.0',
      },
      limits: {
        maxTextureSize: 16384,
        maxColorAttachments: 8,
        computeSupported: true,
        tessellationSupported: true,
        geometryShaderSupported: true,
        anisotropicMax: 16,
        msaaMax: 8,
      },
      quirks: [
        'No native Apple Metal support on TeraScale 2',
        'NUMA dual-socket memory topology requires thread pinning',
        'Requires OVIR-GPU translation from Metal to OpenGL 3.3/4.1',
      ],
    },
    ramMB: 32768,
    storageType: 'SATA SSD',
    efiBitness: '64-bit',
  },
  {
    id: 'mbp-late2013-112',
    systemName: 'MacBook Pro 15-inch Retina (Late 2013)',
    modelIdentifier: 'MacBookPro11,2',
    releaseYear: 2013,
    family: 'Haswell (2013-2014)',
    cpu: {
      model: 'Intel Core i7-4750HQ (Haswell)',
      architecture: 'x86_64',
      microarchitecture: 'Haswell',
      physicalCores: 4,
      logicalThreads: 8,
      baseClockGhz: 2.0,
      maxTurboGhz: 3.2,
      instructionSets: ['MMX', 'SSE4.2', 'AVX2', 'FMA3', 'BMI2', 'AES-NI'],
      tdpWatts: 47,
    },
    gpu: {
      vendor: 'Intel',
      model: 'Intel Iris Pro Graphics 5200 (Haswell GT3e)',
      architecture: 'Haswell Gen7.5 (128MB eDRAM)',
      vramMB: 1536,
      pcieGen: 'Integrated',
      nativeApis: {
        openGL: 'OpenGL 4.1 Core',
        openCL: 'OpenCL 1.2',
        metal: 'Metal 1.2 (Feature Set macOS_GPUFamily1_v1)',
        vulkan: 'Vulkan 1.1 (via Mesa ANV/MoltenVK)',
        directX: 'Direct3D 11.1',
      },
      limits: {
        maxTextureSize: 16384,
        maxColorAttachments: 8,
        computeSupported: true,
        tessellationSupported: true,
        geometryShaderSupported: true,
        anisotropicMax: 16,
        msaaMax: 4,
      },
      quirks: [
        'High memory bandwidth due to 128MB on-package eDRAM crystalwell cache',
        'Unified system memory bandwidth saturation under heavy compute',
      ],
    },
    ramMB: 16384,
    storageType: 'Apple Proprietary PCIe SSD',
    efiBitness: '64-bit',
  },
  {
    id: 'mbp-early2011-81',
    systemName: 'MacBook Pro 13-inch (Early 2011)',
    modelIdentifier: 'MacBookPro8,1',
    releaseYear: 2011,
    family: 'Sandy Bridge (2011)',
    cpu: {
      model: 'Intel Core i5-2415M',
      architecture: 'x86_64',
      microarchitecture: 'Sandy Bridge',
      physicalCores: 2,
      logicalThreads: 4,
      baseClockGhz: 2.3,
      maxTurboGhz: 2.9,
      instructionSets: ['MMX', 'SSE4.2', 'AVX', 'AES-NI'],
      tdpWatts: 35,
    },
    gpu: {
      vendor: 'Intel',
      model: 'Intel HD Graphics 3000 (Gen6)',
      architecture: 'Sandy Bridge Gen6',
      vramMB: 512,
      pcieGen: 'Integrated',
      nativeApis: {
        openGL: 'OpenGL 3.3 Core (macOS capped at 3.3)',
        openCL: 'OpenCL 1.1 (CPU only in early drivers)',
        metal: null,
        vulkan: null,
        directX: 'Direct3D 10.1',
      },
      limits: {
        maxTextureSize: 8192,
        maxColorAttachments: 4,
        computeSupported: false,
        tessellationSupported: false,
        geometryShaderSupported: true,
        anisotropicMax: 8,
        msaaMax: 4,
      },
      quirks: [
        'No hardware tessellation or compute shader support on Gen6',
        'Metal workloads must be simplified and routed through CPU fallback for compute',
      ],
    },
    ramMB: 8192,
    storageType: 'SATA HDD',
    efiBitness: '64-bit',
  },
  {
    id: 'imac-early2008-81',
    systemName: 'iMac 20-inch (Early 2008)',
    modelIdentifier: 'iMac8,1',
    releaseYear: 2008,
    family: 'Early Intel Mac (2006-2009)',
    cpu: {
      model: 'Intel Core 2 Duo E8135 (Penryn)',
      architecture: 'x86_64',
      microarchitecture: 'Penryn',
      physicalCores: 2,
      logicalThreads: 2,
      baseClockGhz: 2.4,
      maxTurboGhz: 2.4,
      instructionSets: ['MMX', 'SSE4.1', 'VT-x'],
      tdpWatts: 35,
    },
    gpu: {
      vendor: 'Nvidia',
      model: 'Nvidia GeForce 8600M GT (Tesla)',
      architecture: 'Tesla (G84M)',
      vramMB: 256,
      pcieGen: 'PCIe 1.1 x16',
      nativeApis: {
        openGL: 'OpenGL 2.1 / 3.3 (Legacy Profile)',
        openCL: null,
        metal: null,
        vulkan: null,
        directX: 'Direct3D 10.0',
      },
      limits: {
        maxTextureSize: 4096,
        maxColorAttachments: 4,
        computeSupported: false,
        tessellationSupported: false,
        geometryShaderSupported: true,
        anisotropicMax: 16,
        msaaMax: 4,
      },
      quirks: [
        'Strict 256MB VRAM cap requires aggressive texture downsampling',
        'No hardware AVX on Penryn CPU',
        'Shader translation must output GLSL 120 or ARB assembly',
      ],
    },
    ramMB: 4096,
    storageType: 'SATA HDD',
    efiBitness: '64-bit',
  }
];
